# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bot Kitchen
email: d@hop.ie
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bot.kitchen" # the base hostname & protocol for your site
twitter_username: botdotkitchen
github_username:  donovanh

permalink: /:title/
paginate: 10
paginate_path: 'page/num'

# Build settings
markdown: kramdown

gems: [jekyll-paginate]

exclude: [_src, node_modules, gulpfile.js]
